#!/usr/bin/env bash

set -e

if [ "$(uname -s)" = "Linux" ]; then
  U_NAME=$(whoami)
  U_UID=$(id -u)
  U_GID=$(id -g)
else
  U_NAME=docker
  U_UID=1000
  U_GID=1000
fi

export U_NAME U_UID U_GID

echo "[ new ] Building docker-compose services"

docker-compose build

docker-compose pull
