#!/usr/bin/env bash

set -e

is_not_running(){
  [ -z `docker-compose ps -q app` ] || [ -z `docker ps -q --no-trunc | grep $(docker-compose ps -q app)` ]
}

# User info for Non-root installation
if [ "$(uname -s)" = "Linux" ]; then
  U_NAME=$(whoami)
  U_UID=$(id -u)
  U_GID=$(id -g)
else
  U_NAME=docker
  U_UID=1000
  U_GID=1000
fi

export U_NAME U_UID U_GID

echo "[ run ] Running docker-compose app service"

if is_not_running; then
  docker-compose down && docker-compose run --rm -p 3000:3000 -p 3035:3035 app bash;
else
  docker exec -it "$(docker-compose ps -q app)" bash;
fi
