#!/usr/bin/env bash

set -e

U_NAME=$(whoami)
U_UID=$(id -u)
U_GID=$(id -g)

export U_NAME U_UID U_GID

echo "[ new ] Running docker-compose app service"

docker-compose run --rm -p 3000:3000 -p 3035:3035 app bash
